#!/bin/busybox sh

# Setup
/bin/busybox mkdir -p /sys /proc /run /tmp /sbin /mnt /etc /pixie
/bin/busybox --install -s
mount -t devtmpfs none /dev
mkdir /dev/pts
mount -t devpts none /dev/pts
mount -t sysfs none /sys
mount -t proc none /proc
ln -s /proc/self/mounts /etc/mtab

error() {
    echo $1
    while true
    do
        /bin/sh
    done
}

MAC=$( ip addr | grep "global eth0" -B1 | head -n1 | cut -d ' ' -f6 )
[ -z "$MAC" ] && error "Cannot find MAC address"
IP="unknown"

dialog --yesno "Am I a worker?" 5 19
if [ "$?" -ne "0" ]
then
    while true; do
        dialog --inputbox "Enter row [1-255]:" 8 22 2> __row
        dialog --inputbox "Enter column [1-255]:" 8 25 2> __col
        ROW=$(cat __row)
        COL=$(cat __col)
        tinycurl "http://""$SERVER_IP""/contestant?mac=""$MAC""&row=""$ROW""&col=""$COL" > __ip 2> __error
        if [ "$?" -eq "0" ]; then
            IP=$(cat __ip)
            break
        else
            dialog --msgbox "Error: $(cat __error)" 6 40
        fi
    done
else
    while true; do
        dialog --inputbox "Enter number [1-255]:" 8 25 2> __num
        NUM=$(cat __num)
        tinycurl "http://""$SERVER_IP""/worker?mac=""$MAC""&num=""$NUM" > __ip 2> __error
        if [ "$?" -eq "0" ]; then
            IP=$(cat __ip)
            break
        else
            dialog --msgbox "Error: $(cat __error)" 6 40
        fi
    done
fi

tinycurl "http://""$SERVER_IP""/reboot_timestamp" > __timestamp
if [ "$?" -ne "0" ]
then
    /bin/reboot || error "error rebooting"
fi
dialog --infobox "Done, waiting to reboot\nI am $IP" 4 27

while true
do
    sleep 10
    tinycurl "http://""$SERVER_IP""/reboot_timestamp" > __timestamp_new
    if [ "$?" -ne "0" ]
    then
        /bin/reboot || error "Error rebooting"
    fi
    cmp __timestamp __timestamp_new 2>/dev/null >/dev/null
    if [ "$?" -ne "0" ]
    then
        /bin/reboot
    fi
done
