#!/bin/bash

[ "$1" == "start" ] || exit

set -e

SERVER_URL=$(cat /proc/cmdline | grep -o 'register=[^ ]*' | cut -f 2 -d =)
[ -z "$SERVER_URL" ] && exit

/bin/wait_for_network.sh $SERVER_URL

echo Press enter to start registration...
read
pixie-register -s $SERVER_URL

echo Done, rebooting now...
sleep 10 # wait to allow reading messages

reboot
