#!/bin/sh

[ "$1" == "start" ] || exit

set -e

SERVER_URL=$(cat /proc/cmdline | grep -o 'push=[^ ]*' | cut -f 2 -d =)
DISK=$(cat /proc/cmdline | grep -o 'disk=[^ ]*' | cut -f 2 -d =)

[ -z "$SERVER_URL" ] && exit
[ -z "$DISK" ] && exit

mount -t efivarfs efivarfs /sys/firmware/efi/efivars

pixie-save-boot-order --boot-order-path boot_order
pixie-push --destination $SERVER_URL -- $DISK boot_order

echo Done, rebooting now...

sleep 10 # wait to allow reading messages

reboot
