#!/bin/sh

[ "$1" == "start" ] || exit

set -e

SERVER_URL=$(cat /proc/cmdline | grep -o 'pull=[^ ]*' | cut -f 2 -d =)
LISTEN_ON=$(cat /proc/cmdline | grep -o 'listen_on=[^ ]*' | cut -f 2 -d =)
UDP_SERVER=$(cat /proc/cmdline | grep -o 'udp_server=[^ ]*' | cut -f 2 -d =)
[ -z "$SERVER_URL" ] && exit

mount -t efivarfs efivarfs /sys/firmware/efi/efivars

time pixie-pull --source $SERVER_URL --listen-on $LISTEN_ON --udp-server $UDP_SERVER
pixie-set-boot-order --boot-order-path boot_order

echo Done, rebooting now...

sleep 10 # wait to allow reading messages

reboot

