#!/bin/bash

[ "$1" == "start" ] || exit

set -e

SERVER_URL=$(cat /proc/cmdline | grep -o 'pull=[^ ]*' | cut -f 2 -d =)
[ -z "$SERVER_URL" ] && exit

/bin/wait_for_network.sh $SERVER_URL

mount -t efivarfs efivarfs /sys/firmware/efi/efivars

pixie-pull --source $SERVER_URL

tar xf efivars.tar

for var in efivars/*
do
  cp -v $var /sys/firmware/efi/efivars
done

efibootmgr -o $(cat efivars/boot_order)

echo Done, rebooting now...

sleep 10 # wait to allow reading messages

reboot

